/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diceprogram;

import javax.swing.JOptionPane;

/**
 *
 * @author 15009199
 */
public class DiceGame extends javax.swing.JFrame {

    Player[] thePlayers = new Player[2];
    /**
     * Creates new form DiceGame
     */
    public DiceGame() {
        initComponents();
        
        for (int i = 0; i < thePlayers.length; i++) {
            thePlayers[i] = new Player();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_welcome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_startGame = new javax.swing.JButton();
        btn_restartGame = new javax.swing.JButton();
        pnl_userData = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_player1Name = new javax.swing.JTextField();
        txt_player0Name = new javax.swing.JTextField();
        btn_start = new javax.swing.JButton();
        pnl_game = new javax.swing.JPanel();
        lbl_player0Name = new javax.swing.JLabel();
        lbl_player1Name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_player0Output = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_player1Output = new javax.swing.JTextArea();
        btn_rollDice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setBackground(new java.awt.Color(102, 255, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Welcome to the Dice Game");

        btn_startGame.setBackground(new java.awt.Color(255, 51, 51));
        btn_startGame.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btn_startGame.setForeground(new java.awt.Color(0, 255, 204));
        btn_startGame.setText("Start");
        btn_startGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startGameActionPerformed(evt);
            }
        });

        btn_restartGame.setFont(new java.awt.Font("Segoe UI", 3, 80)); // NOI18N
        btn_restartGame.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 204), 5, true));
        btn_restartGame.setLabel("Restart");
        btn_restartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restartGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_welcomeLayout = new javax.swing.GroupLayout(pnl_welcome);
        pnl_welcome.setLayout(pnl_welcomeLayout);
        pnl_welcomeLayout.setHorizontalGroup(
            pnl_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_welcomeLayout.createSequentialGroup()
                .addGroup(pnl_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_welcomeLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3))
                    .addGroup(pnl_welcomeLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(pnl_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_startGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_restartGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        pnl_welcomeLayout.setVerticalGroup(
            pnl_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_welcomeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addComponent(btn_startGame)
                .addGap(18, 18, 18)
                .addComponent(btn_restartGame)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel1.setText("Player 1");

        jLabel2.setText("Player 2");

        btn_start.setText("Start");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_userDataLayout = new javax.swing.GroupLayout(pnl_userData);
        pnl_userData.setLayout(pnl_userDataLayout);
        pnl_userDataLayout.setHorizontalGroup(
            pnl_userDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_userDataLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(pnl_userDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_userDataLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_player0Name, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_userDataLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_player1Name))
                    .addComponent(btn_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_userDataLayout.setVerticalGroup(
            pnl_userDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_userDataLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnl_userDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_player0Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(pnl_userDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_player1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btn_start)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        lbl_player0Name.setText("Player 1 Name");

        lbl_player1Name.setText("Player 2 Name");

        txt_player0Output.setColumns(20);
        txt_player0Output.setRows(5);
        jScrollPane1.setViewportView(txt_player0Output);

        txt_player1Output.setColumns(20);
        txt_player1Output.setRows(5);
        jScrollPane2.setViewportView(txt_player1Output);

        btn_rollDice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diceprogram/R.png"))); // NOI18N
        btn_rollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rollDiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_gameLayout = new javax.swing.GroupLayout(pnl_game);
        pnl_game.setLayout(pnl_gameLayout);
        pnl_gameLayout.setHorizontalGroup(
            pnl_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_gameLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnl_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_gameLayout.createSequentialGroup()
                        .addComponent(lbl_player0Name)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_player1Name)
                        .addGap(38, 38, 38))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_gameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_rollDice)
                .addGap(86, 86, 86))
        );
        pnl_gameLayout.setVerticalGroup(
            pnl_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_gameLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnl_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_player0Name)
                    .addComponent(lbl_player1Name))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_rollDice)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_userData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_game, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_game, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_userData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startGameActionPerformed
        // TODO add your handling code here:
                
    }//GEN-LAST:event_btn_startGameActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
        
        pnl_userData.setVisible(false);
        pnl_game.setVisible(true);
        
        thePlayers[0].setPlayerName(txt_player0Name.getText());
        thePlayers[1].setPlayerName(txt_player1Name.getText());
        
        lbl_player0Name.setText(thePlayers[0].getPlayerName());
        lbl_player1Name.setText(thePlayers[1].getPlayerName());
        
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_rollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rollDiceActionPerformed
        // TODO add your handling code here:
        
        txt_player0Output.append(thePlayers[0].getPlayerName() + " rolled a " + thePlayers[0].getPlayerDice(0).rollDice() + " and a " + thePlayers[0].getPlayerDice(1).rollDice() + "\n");
        txt_player1Output.append(thePlayers[1].getPlayerName() + " rolled a " + thePlayers[1].getPlayerDice(0).rollDice() + " and a " + thePlayers[1].getPlayerDice(1).rollDice() + "\n");
        
        if (thePlayers[0].getPlayerDice(0).getCurrentShownFace() == thePlayers[0].getPlayerDice(1).getCurrentShownFace()){
            thePlayers[0].setHasWon(true);
        } 
            
        if (thePlayers[1].getPlayerDice(0).getCurrentShownFace() == thePlayers[1].getPlayerDice(1).getCurrentShownFace()){
            thePlayers[1].setHasWon(true);
        }
        
        if (thePlayers[0].isHasWon() && thePlayers[1].isHasWon()) {
            JOptionPane.showMessageDialog(null, "It was a draw!");
        } else if (thePlayers[0].isHasWon()) {
            JOptionPane.showMessageDialog(null,thePlayers[0].getPlayerName() + " has won!!");
        } else if (thePlayers[1].isHasWon()) {
            JOptionPane.showMessageDialog(null,thePlayers[1].getPlayerName() + " has won!!");
        }
    }//GEN-LAST:event_btn_rollDiceActionPerformed

    private void btn_restartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restartGameActionPerformed
        // TODO add your handling code here:
        
        pnl_userData.setVisible(true);
        
        txt_player0Name.setText("");
        txt_player1Name.setText("");
        
        lbl_player0Name.setText("Player 1 Name");
        lbl_player1Name.setText("Player 2 Name");
        
        txt_player0Output.setText("");
        txt_player1Output.setText("");
        
        
                
    }//GEN-LAST:event_btn_restartGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiceGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_restartGame;
    private javax.swing.JButton btn_rollDice;
    private javax.swing.JButton btn_start;
    private javax.swing.JButton btn_startGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_player0Name;
    private javax.swing.JLabel lbl_player1Name;
    private javax.swing.JPanel pnl_game;
    private javax.swing.JPanel pnl_userData;
    private javax.swing.JPanel pnl_welcome;
    private javax.swing.JTextField txt_player0Name;
    private javax.swing.JTextArea txt_player0Output;
    private javax.swing.JTextField txt_player1Name;
    private javax.swing.JTextArea txt_player1Output;
    // End of variables declaration//GEN-END:variables
}
